"""post ok

Revision ID: 179255c62cbc
Revises: 5a922c350f1d
Create Date: 2025-05-31 18:39:28.518254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179255c62cbc'
down_revision: Union[str, None] = '5a922c350f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'name')
    # ### end Alembic commands ###
