"""post name

Revision ID: 5a922c350f1d
Revises: b2f013f5cd99
Create Date: 2025-05-31 18:24:41.500923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a922c350f1d'
down_revision: Union[str, None] = 'b2f013f5cd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_title_key'), 'post', type_='unique')
    op.add_column('post', sa.Column('name', sa.String(length=200), nullable=False, default='salom'))
    op.create_unique_constraint(None, 'post', ['name'])
    op.drop_column('post', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post', type_='unique')
    op.create_unique_constraint(op.f('post_title_key'), 'post', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_column('post', 'name')
    # ### end Alembic commands ###
